# Generated by Django 5.1.15 on 2026-04-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_workspace_logo_data'),
        ('invoicing', '0002_alter_invoice_discount_type_alter_invoice_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('workspace', 'number')},
        ),
    ]
