# Generated by Django 5.1.15 on 2026-05-21 05:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_errorlog_id_alter_workspaceinvitation_role'),
        ('invoicing', '0005_invoice_refund_fields_partial_refunded_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCatalogItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.workspace')),
            ],
            options={
                'db_table': 'invoicing_service_catalog',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
