# Generated by Django 5.1.15 on 2026-06-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0006_service_catalog_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='subscription_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
