# Generated by Django 5.1.15 on 2026-07-30 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0007_subscription_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='email_template_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
