# Generated by Django 5.1.15 on 2026-07-31 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0008_invoice_email_template_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='next_invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
