# Generated by Django 5.1.15 on 2026-08-07 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0009_invoice_next_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
