# Generated by Django 5.1.15 on 2026-08-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0010_invoice_archived_invoice_archived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='stripe_refund_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
