# Generated by Django 5.1.15 on 2026-08-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0011_invoice_stripe_refund_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='stripe_payment_link',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
