# Generated by Django 5.1.15 on 2026-02-27 02:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_auditlog_id_alter_user_groups_alter_user_id_and_more'),
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='deal',
            name='stage',
            field=models.CharField(choices=[('lead_new', 'Lead – New'), ('discovery_scheduled', 'Discovery Scheduled'), ('discovery_completed', 'Discovery Completed'), ('proposal_sent', 'Proposal Sent'), ('verbal_yes', 'Verbal Yes'), ('active_client', 'Active Client'), ('on_hold', 'On Hold'), ('closed_lost', 'Closed – Lost')], default='lead_new', max_length=30),
        ),
        migrations.AlterField(
            model_name='deal',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.workspace'),
        ),
        migrations.AlterField(
            model_name='stagehistory',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stagehistory',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.workspace'),
        ),
    ]
