# Generated by Django 5.1.15 on 2026-05-16 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_workspace_logo_data'),
        ('pipeline', '0003_deal_pipeline_alert_sent_at_pipelinestageconfigconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinestageconfig',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.workspace'),
        ),
    ]
