# Generated by Django 5.1.15 on 2026-05-21 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_errorlog_id_alter_workspaceinvitation_role'),
        ('pipeline', '0007_deal_extra_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='stage',
            field=models.CharField(default='lead_new', max_length=50),
        ),
        migrations.AlterField(
            model_name='dealprogress',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dealprogress',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.workspace'),
        ),
    ]
