# Generated by Django 5.1.15 on 2026-07-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0008_alter_deal_stage_alter_dealprogress_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinestageconfig',
            name='alert_stop_after_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
