# Generated by Django 5.1.15 on 2026-07-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0009_pipelinestageconfig_alert_stop_after_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='alert_stop_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
