# Generated by Django 5.1.15 on 2026-09-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0010_deal_alert_stop_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='client_alert_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pipelinestageconfig',
            name='client_alert_max_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
