# Generated by Django 5.1.15 on 2026-10-04 20:07

from django.db import migrations, models


def keep_existing_client_alerts_daily(apps, schema_editor):
    """Stages that already emailed clients did so daily — keep that rather than silently
    switching them to the new weekly default; and carry over each deal's last client
    alert so it doesn't get an immediate duplicate."""
    Stage = apps.get_model("pipeline", "PipelineStageConfig")
    Deal  = apps.get_model("pipeline", "Deal")
    Stage.objects.filter(notify_client=True).update(client_frequency="daily")
    for deal in Deal.objects.filter(client_alert_count__gt=0, pipeline_alert_sent_at__isnull=False):
        Deal.objects.filter(pk=deal.pk).update(client_alert_sent_at=deal.pipeline_alert_sent_at)


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0011_deal_client_alert_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='client_alert_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='coach_alert_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipelinestageconfig',
            name='alert_schedule',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pipelinestageconfig',
            name='client_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=10),
        ),
        migrations.AddField(
            model_name='pipelinestageconfig',
            name='coach_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10),
        ),
        migrations.AddField(
            model_name='pipelinestageconfig',
            name='notify_coach',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pipelinestageconfig',
            name='owner_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10),
        ),
        migrations.RunPython(keep_existing_client_alerts_daily, migrations.RunPython.noop),
    ]
