from django.urls import path
from . import views

urlpatterns = [
    path("dashboard/",                            views.dashboard),
    path("workspaces/",                           views.workspace_list),
    path("workspaces/<str:pk>/",                  views.workspace_detail),
    path("workspaces/<str:pk>/users/",            views.workspace_users),
    path("workspaces/<str:pk>/activity/",         views.workspace_activity),
    path("workspaces/<str:pk>/pipeline-stages/",              views.workspace_pipeline_stages),
    path("workspaces/<str:pk>/invoices/",                     views.workspace_invoices),
    path("workspaces/<str:pk>/errors/",                       views.workspace_errors),
    path("workspaces/<str:pk>/reset-password/",               views.workspace_reset_password),
    path("workspaces/<str:pk>/users/<str:user_pk>/set-password/", views.workspace_user_set_password),
    path("workspaces/<str:pk>/activity-types/",               views.workspace_activity_types),
    path("workspaces/<str:pk>/activity-types/<int:type_pk>/", views.workspace_activity_type_detail),
    path("workspaces/<str:pk>/client-statuses/",                      views.workspace_client_statuses),
    path("workspaces/<str:pk>/client-statuses/<int:status_pk>/",      views.workspace_client_status_detail),
    path("workspaces/<str:pk>/client-tags/",                          views.workspace_client_tags),
    path("workspaces/<str:pk>/client-tags/<int:tag_pk>/",             views.workspace_client_tag_detail),
    path("workspaces/<str:pk>/audit-log/",                            views.workspace_audit_log),
    path("registration-tokens/",                  views.registration_tokens),
    path("registration-tokens/<str:pk>/",         views.registration_token_detail),
    path("feedback/",                             views.feedback_list),
    path("feedback/<str:pk>/",                    views.feedback_detail),
    path("feedback/<str:pk>/comment/",            views.feedback_comment),
    path("banners/",                              views.admin_banners),
    path("banners/<int:pk>/",                     views.admin_banner_detail),
    path("platform-invoices/",                                           views.platform_invoices),
    path("platform-invoices/<int:pk>/",                                  views.platform_invoice_detail),
    path("platform-invoices/<int:pk>/send/",                             views.platform_invoice_send),
    path("platform-invoices/<int:pk>/payments/",                         views.platform_invoice_payments),
    path("platform-invoices/<int:pk>/payments/<int:payment_pk>/",        views.platform_invoice_payment_detail),
]
