# Generated by Django 5.1.15 on 2026-06-04 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_email_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=200)),
                ('client_id', models.UUIDField(blank=True, null=True)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('action', models.CharField(choices=[('viewed_notes', 'Viewed Notes'), ('created_note', 'Created Note'), ('updated_note', 'Updated Note'), ('deleted_note', 'Deleted Note'), ('viewed_assessments', 'Viewed Assessments'), ('downloaded_file', 'Downloaded File'), ('uploaded_file', 'Uploaded File'), ('deleted_file', 'Deleted File'), ('viewed_goals', 'Viewed Goals'), ('viewed_feedback', 'Viewed Feedback')], max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.workspace')),
            ],
            options={
                'db_table': 'audit_accesslog',
                'ordering': ['-created_at'],
            },
        ),
    ]
