# Generated by Django 5.1.15 on 2026-05-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_errorlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlog',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workspaceinvitation',
            name='role',
            field=models.CharField(choices=[('platform_admin', 'Platform Admin'), ('business_owner', 'Business Owner'), ('coach', 'Coach'), ('assistant', 'Assistant')], default='coach', max_length=20),
        ),
    ]
