# Generated by Django 5.1.15 on 2026-05-22 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_errorlog_id_alter_workspaceinvitation_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='email_templates',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
