# Generated by Django 5.1.15 on 2026-06-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_email_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='workspace',
            unique_together={('name', 'owner_email')},
        ),
    ]
