# Generated by Django 5.1.15 on 2026-06-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_workspace_owner_email_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceregistrationtoken',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='workspaceregistrationtoken',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
