# Generated by Django 5.1.15 on 2026-06-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_token_recipient_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='pending_activation',
            field=models.BooleanField(default=False),
        ),
    ]
