# Generated by Django 5.1.15 on 2026-06-05 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_pending_activation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workspace',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
