# Generated by Django 5.1.15 on 2026-07-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_workspace_integrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='workspace',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
