# Generated by Django 5.1.15 on 2026-07-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_phone_workspace_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='generic_templates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workspace',
            name='template_use_case_map',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
