# Generated by Django 5.1.15 on 2026-07-31 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_workspace_generic_templates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('platform_admin', 'Platform Admin'), ('business_owner', 'Business Owner'), ('coach', 'Coach'), ('assistant', 'Assistant'), ('limited', 'Limited')], default='coach', max_length=20),
        ),
        migrations.AlterField(
            model_name='workspaceinvitation',
            name='role',
            field=models.CharField(choices=[('platform_admin', 'Platform Admin'), ('business_owner', 'Business Owner'), ('coach', 'Coach'), ('assistant', 'Assistant'), ('limited', 'Limited')], default='coach', max_length=20),
        ),
        migrations.CreateModel(
            name='TabPermission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tab', models.CharField(choices=[('clients', 'Clients'), ('pipeline', 'Pipeline'), ('activities', 'Activities'), ('invoices', 'Invoices'), ('reports', 'Reports'), ('library', 'Library')], max_length=20)),
                ('can_view', models.BooleanField(default=True)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab_permissions', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab_permissions', to='accounts.workspace')),
            ],
            options={
                'db_table': 'user_tab_permissions',
                'unique_together': {('user', 'tab')},
            },
        ),
    ]
