# Generated by Django 5.1.15 on 2026-07-31 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_user_role_alter_workspaceinvitation_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceinvitation',
            name='email_template_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
