# Generated by Django 5.1.15 on 2026-10-03 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_user_address_city_state_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='reschedule_request_ttl_days',
            field=models.PositiveIntegerField(blank=True, default=5, null=True),
        ),
    ]
