# Generated by Django 5.1.15 on 2026-09-25 00:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0023_alter_emaillog_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalLoginCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_login_codes', to='clients.client')),
            ],
            options={
                'db_table': 'portal_logincode',
                'indexes': [models.Index(fields=['client', 'consumed_at'], name='portal_logi_client__1db691_idx')],
            },
        ),
    ]
