# Generated by Django 5.1.15 on 2026-02-27 02:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_auditlog_id_alter_user_groups_alter_user_id_and_more'),
        ('clients', '0002_commitment_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('disc', 'DISC'), ('motivators', 'Motivators'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='visible_to_client',
            field=models.BooleanField(default=False, help_text='Shows in portal (FR-CP-12)'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.workspace'),
        ),
        migrations.AlterField(
            model_name='client',
            name='active_flag',
            field=models.BooleanField(default=False, help_text='Manually set by coach (FR-CRM-03)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='lead_source',
            field=models.CharField(blank=True, choices=[('referral', 'Referral'), ('website', 'Website'), ('linkedin', 'LinkedIn'), ('conference', 'Conference'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='portal_access',
            field=models.BooleanField(default=False, help_text='Enables client portal login (FR-CP-11)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.workspace'),
        ),
        migrations.AlterField(
            model_name='clientgoal',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clientgoal',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='clientgoal',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.workspace'),
        ),
        migrations.AlterField(
            model_name='commitment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='commitment',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.workspace'),
        ),
        migrations.AlterField(
            model_name='goalprogress',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='goalprogress',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.workspace'),
        ),
    ]
