# Generated by Django 5.1.15 on 2026-05-21 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_errorlog_id_alter_workspaceinvitation_role'),
        ('clients', '0004_clientnote_assessment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientnote',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.workspace'),
        ),
    ]
