# Generated by Django 5.1.15 on 2026-07-29 19:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_workspace_generic_templates_and_more'),
        ('clients', '0010_clientnote_visible_to_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMessageDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('intro', models.TextField(blank=True)),
                ('closing', models.TextField(blank=True)),
                ('custom_html', models.TextField(blank=True)),
                ('disable_style', models.BooleanField(default=False)),
                ('show_logo', models.BooleanField(default=True)),
                ('style', models.JSONField(blank=True, default=dict)),
                ('source_template_id', models.CharField(blank=True, max_length=64)),
                ('source_template_name', models.CharField(blank=True, max_length=200)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_drafts', to='clients.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.workspace')),
            ],
            options={
                'db_table': 'clients_messagedraft',
                'ordering': ['-updated_at'],
            },
        ),
    ]
