# Generated by Django 5.1.15 on 2026-07-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_clientmessagedraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='previous_versions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='assessment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
