# Generated by Django 5.1.15 on 2026-07-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_assessment_previous_versions_assessment_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmessagedraft',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
