# Generated by Django 5.1.15 on 2026-07-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_clientmessagedraft_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmessagedraft',
            name='coach_signature',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clientmessagedraft',
            name='include_client_signature_line',
            field=models.BooleanField(default=False),
        ),
    ]
