# Generated by Django 5.1.15 on 2026-07-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_clientmessagedraft_coach_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmessagedraft',
            name='signature_name',
            field=models.CharField(blank=True, help_text="Overrides the coach's account name in the '— {name}' sign-off line", max_length=200),
        ),
    ]
