# Generated by Django 5.1.15 on 2026-07-30 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_clientmessagedraft_signature_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmessagedraft',
            name='client_signature',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clientmessagedraft',
            name='client_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientmessagedraft',
            name='client_signer_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientmessagedraft',
            name='client_signer_user_agent',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='clientmessagedraft',
            name='signed_pdf_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clients.assessment'),
        ),
    ]
