# Generated by Django 5.1.15 on 2026-08-07 01:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_user_address_city_state_zip'),
        ('clients', '0016_clientmessagedraft_client_signature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('invoice', 'Invoice'), ('payment_receipt', 'Payment Receipt'), ('activity_confirmation', 'Session Confirmation'), ('activity_reminder', 'Session Reminder'), ('activity_reschedule', 'Session Rescheduled'), ('activity_cancellation', 'Session Cancelled'), ('client_message', 'Client Message'), ('portal_invite', 'Portal Invite')], max_length=30)),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('related_id', models.CharField(blank=True, max_length=64)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='clients.client')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.workspace')),
            ],
            options={
                'db_table': 'clients_emaillog',
                'ordering': ['-sent_at'],
            },
        ),
    ]
