# Generated by Django 5.1.15 on 2026-08-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='body_html',
            field=models.TextField(blank=True),
        ),
    ]
