# Generated by Django 5.1.15 on 2026-08-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_emaillog_body_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email_2',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_2_ext',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_2_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_ext',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
