# Generated by Django 5.1.15 on 2026-08-29 20:55

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_user_address_city_state_zip'),
        ('clients', '0020_unify_inactive_archive_grey'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='communication_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='client',
            name='referral_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='CommunicationTagConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#2d6a9f', max_length=7)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_tag_configs', to='accounts.workspace')),
            ],
            options={
                'db_table': 'clients_communicationtagconfig',
                'ordering': ['name'],
                'unique_together': {('workspace', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LeadSourceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('is_builtin', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_source_configs', to='accounts.workspace')),
            ],
            options={
                'db_table': 'clients_leadsourceconfig',
                'ordering': ['sort_order', 'label'],
                'unique_together': {('workspace', 'label')},
            },
        ),
    ]
