# Generated by Django 5.1.15 on 2026-08-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0022_clientgoal_visible_to_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='category',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('payment_receipt', 'Payment Receipt'), ('activity_confirmation', 'Session Confirmation'), ('activity_reminder', 'Session Reminder'), ('activity_reschedule', 'Session Rescheduled'), ('activity_cancellation', 'Session Cancelled'), ('client_message', 'Client Message'), ('portal_invite', 'Portal Invite'), ('goal_shared', 'Goal Shared')], max_length=30),
        ),
    ]
