# Generated by Django 5.1.15 on 2026-10-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_alter_emaillog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientnote',
            name='session_date',
            field=models.DateField(blank=True, help_text="Date the session took place — defaults to the note's creation date if left blank", null=True),
        ),
        migrations.AddField(
            model_name='clientnote',
            name='topic',
            field=models.CharField(blank=True, default='', help_text="Short session topic, e.g. 'Weekly check-in' — searchable", max_length=200),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='category',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('payment_receipt', 'Payment Receipt'), ('activity_confirmation', 'Session Confirmation'), ('activity_reminder', 'Session Reminder'), ('activity_reschedule', 'Session Rescheduled'), ('activity_cancellation', 'Session Cancelled'), ('client_message', 'Client Message'), ('portal_invite', 'Portal Invite'), ('goal_shared', 'Goal Shared'), ('note_shared', 'Note Shared')], max_length=30),
        ),
    ]
