# Generated by Django 5.1.15 on 2026-10-07 18:40

from django.db import migrations, models

# Existing rows only had the coarse category — map each to its email type key.
_CATEGORY_TO_USE_CASE = {
    "invoice": "invoice", "payment_receipt": "payment_receipt",
    "activity_confirmation": "confirmation", "activity_reminder": "reminder_24h",
    "activity_reschedule": "reschedule", "activity_cancellation": "cancellation",
    "client_message": "client_communication", "portal_invite": "portal_invite",
    "goal_shared": "goal_shared", "note_shared": "note_shared",
}


def backfill_use_case(apps, schema_editor):
    EmailLog = apps.get_model("clients", "EmailLog")
    for category, use_case in _CATEGORY_TO_USE_CASE.items():
        EmailLog.objects.filter(category=category, use_case="").update(use_case=use_case)


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0024_clientnote_session_date_clientnote_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='audience',
            field=models.CharField(choices=[('client', 'Client'), ('coach', 'Coach / owner'), ('team', 'Team member')], default='client', max_length=10),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=10),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='use_case',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='category',
            field=models.CharField(blank=True, choices=[('invoice', 'Invoice'), ('payment_receipt', 'Payment Receipt'), ('activity_confirmation', 'Session Confirmation'), ('activity_reminder', 'Session Reminder'), ('activity_reschedule', 'Session Rescheduled'), ('activity_cancellation', 'Session Cancelled'), ('client_message', 'Client Message'), ('portal_invite', 'Portal Invite'), ('goal_shared', 'Goal Shared'), ('note_shared', 'Note Shared')], max_length=30),
        ),
        migrations.RunPython(backfill_use_case, migrations.RunPython.noop),
    ]
