# Generated by Django 5.1.15 on 2026-02-27 02:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_auditlog_id_alter_user_groups_alter_user_id_and_more'),
        ('activities', '0001_initial'),
        ('pipeline', '0002_alter_deal_id_alter_deal_stage_alter_deal_workspace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='pipeline.deal'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('appointment', 'Appointment'), ('task', 'Task'), ('call', 'Call'), ('session', 'Session'), ('training', 'Training'), ('travel', 'Travel'), ('custom', 'Custom')], max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes — not visible to client'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='recurrence_id',
            field=models.UUIDField(blank=True, help_text='Parent activity for recurring series', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='rrule',
            field=models.TextField(blank=True, help_text='RRULE string e.g. FREQ=WEEKLY;COUNT=12'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('missed', 'Missed Session'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.workspace'),
        ),
    ]
