# Generated by Django 5.1.15 on 2026-05-16 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_workspace_logo_data'),
        ('activities', '0005_activitytypeconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytypeconfig',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.workspace'),
        ),
    ]
