# Generated by Django 5.1.15 on 2026-05-16 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_alter_activitytypeconfig_workspace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitytypeconfig',
            name='default_duration_mins',
        ),
    ]
