# Generated by Django 5.1.15 on 2026-06-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_activity_repeat_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Zoom / Meet / Teams join URL', max_length=500),
        ),
    ]
