# Generated by Django 5.1.15 on 2026-07-30 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_calendar_rsvp_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('appointment', 'Appointment'), ('task', 'Task'), ('call', 'Call'), ('session', 'Session'), ('training', 'Training'), ('travel', 'Travel'), ('custom', 'Custom'), ('client_communication', 'Client Communication')], max_length=20),
        ),
    ]
