# Generated by Django 5.1.15 on 2026-07-30 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_alter_activity_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='email_template_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
