# Generated by Django 5.1.15 on 2026-08-26 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_user_address_city_state_zip'),
        ('activities', '0014_activity_email_template_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#1a2f4e', max_length=7)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.workspace')),
            ],
            options={
                'db_table': 'activities_affiliationconfig',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('workspace', 'name')},
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='affiliation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='activities.affiliationconfig'),
        ),
    ]
