# Generated by Django 5.1.15 on 2026-10-03 21:44

import apps.activities.models
import django.contrib.postgres.constraints
from django.conf import settings
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_user_address_city_state_zip'),
        ('activities', '0016_activity_requested_start_at_coachavailabilityrule'),
        ('clients', '0023_alter_emaillog_category'),
        ('pipeline', '0011_deal_client_alert_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Required for the exclusion constraint below — it combines a range type
        # (tstzrange) with a plain equality column (coach) in one GiST index, which
        # needs btree_gist's operator classes for the equality half. Not auto-added by
        # makemigrations; Django's own docs for ExclusionConstraint call out adding this
        # by hand. One-time, cluster-level (CREATE EXTENSION), not per-table.
        BtreeGistExtension(),
        migrations.AddConstraint(
            model_name='activity',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ['scheduled', 'rescheduled'])), expressions=[(apps.activities.models._TsTzRange(models.F('start_at'), models.F('end_at')), '&&'), ('coach', '=')], name='activity_no_overlapping_coach_bookings'),
        ),
    ]
