# Generated by Django 5.1.15 on 2026-10-03 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0017_activity_activity_no_overlapping_coach_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
