# Generated by Django 5.1.15 on 2026-09-16 15:36
# Trimmed by hand to only the DemoLead table — the autodetector also picked up unrelated
# pre-existing drift on MaintenanceBanner/PlatformInvoice/PlatformPayment (Meta.ordering,
# implicit id field) that predates this change and isn't part of it; left untouched here
# so this migration doesn't carry someone else's in-flight schema changes.

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0007_platforminvoice_billing_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('login_count', models.PositiveIntegerField(default=0)),
                ('tour_started', models.BooleanField(default=False)),
                ('tour_completed', models.BooleanField(default=False)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'superadmin_demolead',
                'ordering': ['-last_seen_at'],
            },
        ),
    ]
